### ISSUE TITLE
error during use of bsc_segmentSubCortical_v2.m

### ISSUE THREAD

**Issue by bacaron** [DanNBullock/wma_tools#6]
When attempting to run your segmentation, I'm running into an issue with line 122 of this function (see below). The error message I receive is: 'Error using == \n Matrix dimensions must agree'

https://github.com/DanNBullock/wma_tools/blob/25bb3b3f9e2948ab10a2daf59a8f7ab4e2b23678/bsc_segmentSubCortical_v2.m#L122

**Comment by DanNBullock** [comment]
I would expect this to occur when the category prior function fails to find any within hemisphere frontal to subcortical connections.  Or at least whatever the name specified here is ('frontal_to_subcortical').  This is surprising because there's usually a great many tracts that meet this criteria (i.e. thalamaco-cortical connections).  Might mean something is wrong with your data.  Regardless, the oveararching problem is that this was not a safe call in the event that no streamlines are found.  Remedied by using https://github.com/DanNBullock/wma_tools/blob/master/bsc_extractStreamIndByName.m

Will update and include in next recompile.

7/20/2019 Note:  local github repo appears to be corrupt.

**Comment by DanNBullock** [comment]
I believe this was fixed on July 20 with the addition of calls to https://github.com/DanNBullock/wma_tools/blob/master/bsc_extractStreamIndByName.m
